[feature/100]: 경로 리뷰 구현
TravelPlan-Project/TravelPlan pull request #104
Opened 2021-04-11 03:32 UTC by donup3

2021-04-14 04:04 UTC, donup3 commented
@labyu 
경로 리뷰 리스트 조회는 간단하게만 구현해놨습니다. 
리스트 조회에서 N+1 문제를 해결할 방법을 찾아봐야 할거같아요

2021-04-14 08:40 UTC, donup3 commented
일대다인 상황에서 fetch join은(Collection fetch join) 사용안하는게 좋을 것 같아서 default_batch_fetch_size 설정만 추가해놨습니다

2021-04-14 10:07 UTC, labyu requested changes

2021-04-14 10:07 UTC, labyu commented on backend/api/src/main/java/me/travelplan/config/AWSS3Config.java
> +    public S3Client getS3Client() {
메소드명 s3Client가 아니고 getS3Client로 하신 이유가 있으신지 궁금합니다. 일반적으로 `@Bean` 선언할 때에는 `s3Client`로 사용하는 것을 더 많이 본 것 같습니다.

2021-04-14 10:07 UTC, labyu commented on backend/api/src/main/java/me/travelplan/config/jpa/BaseEntity.java
> +    }
제 이슈에서 BaseEntity에 `@Setter`를 추가했습니다. 이 엔티티 디자인을 한번 같이 점검해보면 좋을 것 같습니다.

`@Getter`, `@Setter`, `@~Constructor`, `@Builder` 사용 어떻게 할 것인지

2021-04-14 10:07 UTC, labyu commented on backend/api/src/main/java/me/travelplan/service/file/File.java
>  public class File extends BaseEntity {
제가 BaseEntity에 SoftDelete처리 해놓은 것들이 상속에서는 동작을 안하는 것 같습니다. 심지어 SQL문도 틀려놓아서 제 이슈에서 수정해놓았습니다. File Entity 및 RouteReview 엔티티 SoftDelete처리 부탁드립니다.

예시 :
https://github.com/baruntravel/baruntravel/blob/develop/backend/api/src/main/java/me/travelplan/service/place/PlaceReview.java

2021-04-14 13:33 UTC, donup3 commented on backend/api/src/main/java/me/travelplan/config/AWSS3Config.java
> +    public S3Client getS3Client() {
별다른 의미는 없고 하다보니 이름을 이렇게 지었네요.  머지 컨플릭트 없애면서 수정해놓겠습니다~

2021-04-14 13:34 UTC, donup3 commented on backend/api/src/main/java/me/travelplan/service/file/File.java
>  public class File extends BaseEntity {
네 이 부분도  s3Client 수정하면서 같이 추가해야겠네요

2021-04-15 03:02 UTC, labyu approved these changes

2021-04-15 03:07 UTC, merged