[feature/120] 경로 즐겨찾기(좋아요) 기능 구현(생성,수정)
TravelPlan-Project/TravelPlan pull request #122
Opened 2021-04-17 03:26 UTC by donup3

2021-04-18 08:53 UTC, donup3 commented
경로 리스트를 조회하는 api 에서 로그인유저가 좋아요를 눌렀는지 안눌렀는지를 알려주는 정보를 포함하려다보니 RouteMapper에서 로그인유저가 좋아요를 눌렀는지에 대한 간단한 로직이 들어갔습니다. mapper쪽이 아니라 다른 곳에서 처리를 하려고 했는데 마땅한 방법이 안떠올라서 후에 괜찮은 방법이 있다면 수정해야할 것 같아요. 
해결방법으로 로그인 유저가 좋아요를 눌렀는 지에 대한 api를 따로 분리하는 방법이 있었지만 일단 경로 리스트 조회할 때 한번에 보여줄 수 있도록 했습니다

2021-04-18 11:26 UTC, labyu requested changes

2021-04-18 11:26 UTC, labyu commented on backend/api/src/main/java/me/travelplan/service/route/RouteMapper.java
> +                    list.setLikeCheck(routeLike.getCreatedBy().getId().equals(loginUser.getId()) && routeLike.isLikeCheck()));
PR 코멘트로 남겨주신 고민 보고 저도 고민해보았는데요.

Route Class에서 Public Method로 isLike(User user); 메소드를 정의하면 어떨까요? 현재 이 Mapper 메소드의 파라미터로 loginUser를 받고 있기 때문에 코드수정도 많지 않을 것 같습니다.

```java
@Entity
class Route {
  ...
  public isLike(User user) {
    .. 현재 이 경로를 좋아하고있는지 찾는 로직
  }
...
}
```

2021-04-18 11:26 UTC, labyu commented on backend/api/src/main/java/me/travelplan/service/route/RouteLike.java
> +}
좋아요를 row의 exists 여부가 아닌 boolean으로 하신 이유가 있으신지 궁금합니다.

좋아요 테이블이 결국 User - Route 엔티티간의 릴레이션 이외의 기능은 하지 않는 것 같은데요. 좋아요를 취소 했을 때 row를 delete처리해도 같은 기능을 구현할 수 있을 것 같습니다. 좋아요여부를 확인하기 위해 Exists && boolean == true 이렇게 두번 조건을 확인해야하는 것이 조금 오버헤드가 있는 것 같아요.

2021-04-18 12:06 UTC, donup3 commented on backend/api/src/main/java/me/travelplan/service/route/RouteMapper.java
> +                    list.setLikeCheck(routeLike.getCreatedBy().getId().equals(loginUser.getId()) && routeLike.isLikeCheck()));
참고해서 다시 확인해보겠습니다!

2021-04-18 12:11 UTC, donup3 commented on backend/api/src/main/java/me/travelplan/service/route/RouteLike.java
> +}
네 그 부분은 삭제로 처리 하는 것이 좋아보이네요.

2021-04-19 00:46 UTC, labyu approved these changes

2021-04-19 01:26 UTC, merged