[feature/140] 장소 상세 정보 업데이트 기능
TravelPlan-Project/TravelPlan pull request #142
Opened 2021-04-27 14:12 UTC by labyu

2021-05-02 06:57 UTC, labyu commented
속도가 생각보다 느리지 않아서 동기적으로 처리해놓았는데 필요하다면 비동기로 리팩토링하면 될 것 같습니다.

ERD 수정했습니다.
- https://www.erdcloud.com/d/Hi5oXfeRZNbFqXaSc
-

2021-05-03 02:13 UTC, donup3 requested changes

2021-05-03 02:13 UTC, donup3 commented on backend/api/src/main/java/me/travelplan/service/kakaomap/KakaoMapPlace.java
> +    }
접근제어자를 사용하지 않은 이유가 있을까요??

2021-05-03 02:14 UTC, donup3 approved these changes

2021-05-03 02:41 UTC, donup3 requested changes

2021-05-03 02:41 UTC, donup3 commented on backend/api/src/main/java/me/travelplan/service/kakaomap/KakaoMapPlace.java
> +    }
접근 제어자를 사용하지 않은 이유가 있을까요??

2021-05-03 11:01 UTC, donup3 commented on backend/api/src/main/java/me/travelplan/service/place/PlaceService.java
> +        placeRepository.save(place);
placeRepository.save를 사용하지 않아도 jpa 변경감지로 인해 place entity에 update 쿼리가 실행될 것 같습니다

2021-05-04 08:45 UTC, labyu commented on backend/api/src/main/java/me/travelplan/service/place/PlaceService.java
> +        placeRepository.save(place);
아하 맞네용 ㅎ,ㅎ

2021-05-04 08:46 UTC, labyu commented on backend/api/src/main/java/me/travelplan/service/kakaomap/KakaoMapPlace.java
> +    }
깜빡했습니다! 추가하겠습니다 ㅎㅎ

2021-05-04 08:52 UTC, donup3 approved these changes

2021-05-05 01:17 UTC, merged