[feature/153] http 파일 추가, 경로 리뷰 좋아요 기능 구현
TravelPlan-Project/TravelPlan pull request #155
Opened 2021-05-03 06:26 UTC by donup3

2021-05-04 01:34 UTC, labyu requested changes

2021-05-04 01:34 UTC, labyu commented on backend/api/src/main/java/me/travelplan/service/route/RouteReview.java
> +
Cascade DELETE 대신 All을 사용하신 이유가 있을까요?

2021-05-04 01:34 UTC, labyu commented on backend/api/src/main/java/me/travelplan/service/route/RouteReviewLike.java
> +    }
create method에서 빌더로 한번에 처리하지 않고 setter를 사용하여 처리하신 이유가 있으신지 궁금합니다.

2021-05-04 01:34 UTC, labyu commented on backend/api/src/main/java/me/travelplan/service/route/RouteService.java
> +    }
method 네임은 createOrUpdate 인데, 동작은 createOrDelete 인 것 같습니다.

2021-05-04 01:44 UTC, donup3 commented on backend/api/src/main/java/me/travelplan/service/route/RouteReviewLike.java
> +    }
양방향 연관관계라 양쪽에 값을 넣어주기 위해서 메서드를 만들어서 사용했습니다

2021-05-04 01:44 UTC, donup3 commented on backend/api/src/main/java/me/travelplan/service/route/RouteReview.java
> +
편의상 ALL로 해놓긴 했는데 DELETE로 해도 상관없을 거 같네요

2021-05-04 01:45 UTC, donup3 commented on backend/api/src/main/java/me/travelplan/service/route/RouteService.java
> +    }
네 이 부분은 모든 좋아요 메서드 이름을 수정해는 것이 좋아보입니다

2021-05-05 01:19 UTC, labyu approved these changes

2021-05-05 07:48 UTC, merged